import sys
import os
import streamlit as st
import pandas as pd
import sqlite3
import xgboost as xgb
from docx import Document

sys.path.append("src")
from search_hybrid import get_hybrid_scores

st.set_page_config(layout="wide", page_title="INDIA.RUNS Candidate Ranking")
st.title("AI Candidate Ranking System - Final Output")

st.markdown("""
### 10/10 ML Architecture
This application displays the final **100 Diverse Candidates** generated by our 7-Stage Machine Learning Pipeline.
The pipeline utilizes Knowledge Distillation, XGBoost, Cross-Encoders, and Maximal Marginal Relevance to perfectly rank candidates based on deep semantic match, explicit skills, behavioral markers, and team diversity.
""")

try:
    df = pd.read_csv("team_submission.csv")
    
    st.success(f"Successfully loaded {len(df)} candidates from team_submission.csv")
    
    # Format the dataframe for beautiful UI
    df.rename(columns={
        "candidate_id": "Candidate ID",
        "rank": "Rank",
        "score": "Final Score",
        "reasoning": "AI Reasoning & Highlight Flags"
    }, inplace=True)
    
    st.dataframe(df, use_container_width=True, height=800)
    
except FileNotFoundError:
    st.error("team_submission.csv not found. Please run 'python src/generate_submission.py' first.")